import '../styles/globals.css'
import type { Metadata } from 'next'
import { Chakra_Petch as ChakraPetch, Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { MenuContextProvider } from '@/contexts/menu-context'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '700'],
})

const alt = ChakraPetch({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-alt',
})

export const metadata: Metadata = {
  title: 'apperize',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <MenuContextProvider>
      <html
        lang="pt-BR"
        className="antialiased scroll-smooth"
        suppressHydrationWarning
      >
        <body
          className={`${inter.variable} ${alt.variable} 
        font-sans text-foreground bg-background scrollbar scrollbar-track-background-alt scrollbar-thumb-background-alt-dark 
      `}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="relative">{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </MenuContextProvider>
  )
}
