import '../styles/globals.css'
import type { Metadata } from 'next'
import { Chakra_Petch as ChakraPetch, Inter } from 'next/font/google'
import { Providers } from '@/providers'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '700'],
})

const alt = ChakraPetch({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-alt',
})

export const metadata: Metadata = {
  title: 'Apperize',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="pt-BR" className="scroll-smooth ">
        <body
          className={`${inter.variable} ${alt.variable} 
        font-sans text-foreground scrollbar-thin scrollbar-track-scroll-track scrollbar-thumb-scroll-thumb
      `}
        >
          <main className="relative">{children}</main>
        </body>
      </html>
    </Providers>
  )
}
